### ISSUE TITLE
How to change binding IP address?

### ISSUE THREAD

**Issue by TejaRamachandran** [EclecticIQ/OpenTAXII#52] opened 2016-12-26 12:22 UTC
Hi Team, 

I am totally new to this OpenTaxII Git- Somehow, I successfully installed the whole set up in a ubuntu VM. But I cant access the taxii server VIA my host machine. Then  i came to know the address to binded(lo Localhost). can anyone help me change this binding to run on my "eth1" interface. 

I have changed the defaults.yml files. Then also its not replicating. Thanks in advance.

**Comment by wbolster** [comment] 2016-12-27 08:43
how are you starting the daemon?

gunicorn? read https://opentaxii.readthedocs.io/en/stable/running.html#production-mode and change the `--bind` parameter.

docker? read https://opentaxii.readthedocs.io/en/stable/docker.html and change the `OPENTAXII_DOMAIN` parameter.

**Comment by TejaRamachandran** [comment] 2016-12-29 10:55
Thanks for your response. 
I am using docker to run the server, I can able to authenticate the server and access server at all interface as well. 

I have read that by default some basic services are running under the docker, when i am running the taxii-discovery against my localhost Taxii server - i got 404 as a response. can you help me here as well. 

My use case here is i want to setup a TaxII server which will receive IOC data via push method from one taxii client and another taxii client will poll the IOC data.

`root@ubuntu:/home/Taxii# taxii-discovery --username xxx --password xxxxx --path http://localhost:9000/services/discovery --port 9000
2016-12-29 16:13:24,933 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2016-12-29 16:13:24,938 INFO: Starting new HTTP connection (1): localhost
2016-12-29 16:13:24,954 ERROR: HTTP Error: status code 404
`
[https://raw.githubusercontent.com/EclecticIQ/OpenTAXII/master/examples/services.yml](url) [https://raw.githubusercontent.com/EclecticIQ/OpenTAXII/master/examples/collections.yml](url)

**Comment by traut** [comment] 2016-12-29 11:00
if you look at that config that you linked - https://raw.githubusercontent.com/EclecticIQ/OpenTAXII/master/examples/services.yml - you will see that there are no services with address `/services/discovery` defined. That's why you're getting 404 when trying to send a discovery request to `/services/discovery`.

Please use one of the defined discovery service, with address `/services/discovery-a`.

Obviously, if you changed the default configuration somehow or you have your own configuration, you may have a different address

**Comment by TejaRamachandran** [comment] 2016-12-29 13:29
Thanks Traut, By default docker is not having any services and collection configured. But i have configured it by using docker documentation. when i ran taxii-discovery on my server i got response as we expect. Please find the attachment. 

Kindly clarify me - Is all my configuration is done and TaxII server is good to go for below point:

- Any TaxII client can able to pull and push IOC on my TaxII server?

Thanks in advance. 

[taxii-discovery response.txt](https://github.com/EclecticIQ/OpenTAXII/files/677115/taxii-discovery.response.txt)

**Comment by traut** [comment] 2016-12-29 13:37
@TejaRamachandran if your intent is to use example configuration, you're all set.

Note that the better idea is to tune services and collections configuration to your specific needs. For instance, maybe you do not need 2 Inbox services. Example configuration was designed to show variety of possible options, not to be used as is in production.

**Comment by TejaRamachandran** [comment] 2017-01-16 09:03
@traut  - When i am polling the IOC data TaxII server from our SIEM solution. I am getting error nothing to poll blocks found (No Collection Services found). But i am running default collection service. Can you help me how to trouble shoot this.? and is it possible can you help me how to create basic inbox service which can receive IOC from one TI server and same can be polled to another TI server.?

And One more question - How to see the IOC data stored in this Open TaxII server(Running in docker) - The reason is one of our TI product pushing IOC to OT server in inbox-a service on (urn:custom.example.com:json:0.0.1) .

**Comment by traut** [comment] 2017-01-16 14:06
@TejaRamachandran it seems you're not clear on how to configure your services. Also the error shows that either you're querying wrong service (Collection is not attached to it), or you're using incorrect collection name.

Please read [TAXII Services spec](https://taxiiproject.github.io/releases/1.1/TAXII_Services_Specification.pdf) to understand how services are tied together. Example services configuration [provided](https://github.com/EclecticIQ/OpenTAXII/blob/master/examples/services.yml) with OpenTAXII shows you all the possibilities you have, please use it as a template for your own configuration (same for [Collection config](https://github.com/EclecticIQ/OpenTAXII/blob/master/examples/collections.yml) provided). I'm afraid I do not have time to help you more than that. Please take a look at our platform description (https://www.eclecticiq.com/platform), maybe it may solve some of your problems out of the box.  

Regarding your last question: you can use any SQL client to peek into the DB or pull the data using Cabby. OpenTAXII does not have any other tools for that just yet.

// I'm going to close this ticket because original issue was solved and discussion diverged.

**Closed by traut** 2017-01-16 14:06 UTC
Labels: question

**Comment by rameshyuvaraj** [comment] 2017-06-08 07:48
Hi Teja or Anyone else ! Please help me out,

I am new to OpenTaxii as well. I have successfully setup the opentaxii by following https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.ubuntu1604.txt

![image](https://user-images.githubusercontent.com/11936908/26917325-79999ab8-4c4b-11e7-8944-4de4f76ab5a4.png)

It is connected to MISP running in the same server in default port localhost
Im able to access my MISP web interface from my host machine using the ip !
![image](https://user-images.githubusercontent.com/11936908/26917353-9181e28e-4c4b-11e7-9d42-6959608c3c94.png)

But i am not able to send a request from my host machine to the openTaxii. 
![image](https://user-images.githubusercontent.com/11936908/26917462-062d75c6-4c4c-11e7-863f-33cc929800ef.png)

I tried using gunicorn but not able to run as stand alone app im getting some error like this
![image](https://user-images.githubusercontent.com/11936908/26917633-ad6c9c7c-4c4c-11e7-920c-945cfa05c981.png)

Any help appreciated. If i am able to access the discovery url then i can configure opentaxii server in our project to get feeds from opentaxii on a regular interval which is like configuring a hailataxii services

**Comment by traut** [comment] 2017-06-08 07:50
@rameshyuvaraj I see there is a MySQL error in the log. Have you fixed that one already?

**Comment by rameshyuvaraj** [comment] 2017-06-08 09:00
@traut No i did not fixed it. I dont know from where or why this error is coming. If i run opentaxii-run-dev it is working fine. using gunicorn im getting the above error

**Comment by traut** [comment] 2017-06-08 09:49
@rameshyuvaraj did you run OpenTAXII against sqlite3 in `opentaxii-run-dev` mode and against MySQL in "normal" deployment mode with gunicorn? That error clearly states that there is an issue with the value you provided and your DB schema. To me it looks like environment configuration issue

**Comment by rameshyuvaraj** [comment] 2017-06-08 15:03
The error is gone after restarting the VM. gunicorn command is working. But even then im not able to access opentaxii (IP:9000/services/index) from outside VM. Giving the site cant be reached error.

**Comment by traut** [comment] 2017-06-08 15:15
@rameshyuvaraj as I said, please check on which network interface your OpenTAXII is running

**Comment by mcamachotw** [comment] 2018-02-15 17:50
Hello @traut 
One question how can I change the "Service Address http://localhost:9000 by Service Address http://192.168.37.141:9000" I'm trying to create a server taxii, but this part is not clear for me, so how can I change the "Service Address and  Poll Address" by  http://192.168.37.141:9000/, Could you please help me?

1. I define use gunicorn and I executed liki this,
      gunicorn opentaxii.http:app --bind 192.168.37.141:9000
2. when I review the discovery and collections appear me this information,

taxii-discovery --path http://192.168.37.141:9000/services/dicovery-a
=== Service Instance ===
  Service Type: DISCOVERY
  Service Version: urn:taxii.mitre.org:services:1.1
  Protocol Binding: urn:taxii.mitre.org:protocol:https:1.0
  Service Address: http://localhost:9000/services/dicovery-a
  Message Binding: urn:taxii.mitre.org:message:xml:1.0
  Message Binding: urn:taxii.mitre.org:message:xml:1.1
  Available: True
  Message: None

taxii-collections --path http://192.168.37.141:9000/services/collection-management-a

=== Data Collection Information ===
  Collection Name: XXXXXX
  Collection Type: DATA_SET
  Available: True
  Collection Description: none
  Supported Content:   urn:stix.mitre.org:xml:1.0
  === Polling Service Instance ===
    Poll Protocol: urn:taxii.mitre.org:protocol:https:1.0
    Poll Address: http://localhost:9000/services/collection-management-a
    Message Binding: urn:taxii.mitre.org:message:xml:1.1
==================================

Regards,

**Comment by traut** [comment] 2018-02-28 11:47
@mcamachotw did you look at OpenTAXII [configuration file](http://www.opentaxii.org/en/stable/configuration.html#configuration)? first line

**Comment by mcamachotw** [comment] 2018-02-28 12:35
@traut Understood, thanks.
