### ISSUE TITLE
Incorrect datetime value for column timestamp_label

### ISSUE THREAD

**Issue by hjklz** [eclecticiq/OpenTAXII#71] opened 2017-05-18 22:01 UTC
I get the following error when attempting a taxii-push.

(1292, \"Incorrect datetime value: '2017-05-18 20:44:03.599933+00:00' for column 'timestamp_label' at row 1\") 

The strange thing is when I run 
opentaxii-run-dev 
taxii-push -f sample.xml --path http://localhost:9000/services/inbox --dest collection

I do not get the error. So I guess the dev version doesn't actually update the database/only uses the default config.

It occurs when I use
gunicorn opentaxii.http:app --bind 192.168.56.2:9000
taxii-push -f sample.xml --path http://192.168.56.2:9000/services/inbox --dest collection

I do suspect it has something to do with the fact that SQLAlchemy doesnt comply with mysql datetime standard (http://stackoverflow.com/questions/15821953/mysql-and-python-datetime)

Any assistance would be appreciated, I assume the fix would be to just remove the timezone for that field somewhere...

Thanks

**Comment by traut** [comment] 2017-05-22 14:25
@hjklz thanks for reporting this!

So everything is fine when you're running `opentaxii-run-dev` (that uses sqlite3) but things break when you run OpenTAXII via gunicorn with MySQL as a backend. Did I understand correctly?

Thanks for pointing to that StackOverflow question. I'll look into it.

**Comment by hjklz** [comment] 2017-05-23 17:06
Yes, that's right. When I try to push events with MySQL as the backend database it breaks with the error I state above.

**Comment by traut** [comment] 2017-06-19 10:25
@hjklz sorry for the delay on this, I'll take a look

**Comment by arcsector** [comment] 2017-11-27 19:46
At least for my testing environment, mysql no longer gives this error. @hjklz can you verify?

**Comment by traut** [comment] 2018-06-03 21:46
closing this since I can not reproduce. please comment if you can reproduce it in new [release 0.1.10](https://github.com/eclecticiq/OpenTAXII/releases/tag/0.1.10).

**Closed by traut** 2018-06-03 21:46 UTC
Labels: mysql
