### ISSUE TITLE
ERROR: Extra content at the end of the document (taxii-poll command)

### ISSUE THREAD

**Issue by maxymax68** [EclecticIQ/OpenTAXII#64] opened 2017-04-12 08:05 UTC
I get 
```
2017-04-12 09:43:11,079 ERROR: Extra content at the end of the document, line 655441, column 53 (line 655441)
```
After the taxii-poll command prints out lines extracted from OpenTAXII server.
Many thanks in advance for your help.

**Comment by traut** [comment] 2017-04-12 08:49
this looks like an issue with the XML content block. Could you verify that it is well formed?

**Comment by maxymax68** [comment] 2017-04-12 09:00
The error is the output of command taxi-poll and the data presented comes from OpenTAXII server.
Who do I check if the persisted data is properly formatted?
Many thanks

**Comment by traut** [comment] 2017-04-12 09:08
either check XMLs you pushed into the server or read XMLs directly from SQL DB that you use as OpenTAXII's backend

**Comment by traut** [comment] 2017-04-25 11:46
any new developments with this issue, @maxymax68?

**Comment by maxymax68** [comment] 2017-04-25 12:19
The issue is still there. No error when posting, but error when using taxii-poll command. This looks very weird.

**Comment by traut** [comment] 2017-06-19 10:26
@maxymax68 and you're 100% sure that XML content block you're trying to poll is valid XML?

**Comment by Danko90** [comment] 2017-07-04 15:00
Hi,
I have the same issue when I try to poll from FS-ISAC repository. I downloaded the repository and validated it. Sometimes I get also this error:
```
http.client.IncompleteRead: IncompleteRead(0 bytes read, 8000 more expected)
```

**Comment by traut** [comment] 2017-07-04 15:04
@Danko90 I think this is a combination Soltra Edge's issues:
- it does not page response, so it packs all content blocks into one potentially multi-gig XML. Serving this might be slow, so it might hit closed connections somewhere on the way (`IncompleteRead(0 bytes read, 8000 more expected)` error)
- sometimes returned XML will be invalid (`Extra content at the end of the document, line 655441` error). I've seen it with FoxIT feed, for example

Note that I do not know the cause of these errors with 100% certainty since I do not have Soltra Edge instance to test/debug

**Closed** 2017-10-15 21:45 UTC
