### ISSUE TITLE
`opentaxii-delete-blocks` not deleting records from `collection_to_content_block`

### ISSUE THREAD

**Issue by dhkron** [eclecticiq/OpenTAXII#93] opened 2017-11-30 16:57 UTC
Apparently when deleting `content-blocks` by using the python script `opentaxii-delete-blocks`, only the content blocks themselves are deleted.
The connection between collection and content blocks is *not* deleted.

To reproduce:
1. Push a record to a collection using `cabby`
2. Delete all content blocks from the collection by `opentaxii-delete-blocks`
3. Try to insert again -> will throw an exception.

This is the exception I see:
```{
  "event": "Status exception",
  "logger": "opentaxii.middleware",
  "level": "warning",
  "timestamp": "2017-11-30T16:45:35.240165Z",
  "exception": "Traceback (most recent call last):
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1182, in _execute_context
    context)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py\", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: collection_to_content_block.collection_id, collection_to_content_block.content_block_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/services/abstract.py\", line 83, in process
    response_message = handler.handle_message(self, message)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 126, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 65, in handle_message
    inbox_message_id=inbox_message.id if inbox_message else None)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/persistence/manager.py\", line 160, in create_content
    content, collection_ids=collection_ids, service_id=service_id)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/persistence/sqldb/api.py\", line 249, in create_content_block
    self._attach_content_to_collections(content, collection_ids)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/persistence/sqldb/api.py\", line 267, in _attach_content_to_collections
    collections=new_collections.count())
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 3089, in count
    return self.from_self(col).scalar()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2843, in scalar
    ret = self.one()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2814, in one
    ret = self.one_or_none()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2784, in one_or_none
    ret = list(self)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2854, in __iter__
    self.session._autoflush()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 1422, in _autoflush
    util.raise_from_cause(e)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 187, in reraise
    raise value
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 1412, in _autoflush
    self.flush()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 2192, in flush
    self._flush(objects)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py\", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 187, in reraise
    raise value
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 2276, in _flush
    flush_context.execute()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py\", line 389, in execute
    rec.execute(self)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py\", line 503, in execute
    self.dependency_processor.process_saves(uow, states)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/dependency.py\", line 1092, in process_saves
    secondary_update, secondary_delete)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/dependency.py\", line 1136, in _run_crud
    connection.execute(statement, secondary_insert)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 945, in execute
    return meth(self, multiparams, params)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py\", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1189, in _execute_context
    context)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1402, in _handle_dbapi_exception
    exc_info
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 186, in reraise
    raise value.with_traceback(tb)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1182, in _execute_context
    context)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py\", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: collection_to_content_block.collection_id, collection_to_content_block.content_block_id [SQL: 'INSERT INTO collection_to_content_block (collection_id, content_block_id) VALUES (?, ?)'] [parameters: (1, 1)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File \"/usr/local/lib/python3.5/dist-packages/flask/app.py\", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File \"/usr/local/lib/python3.5/dist-packages/flask/app.py\", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/middleware.py\", line 76, in wrapper
    return _process_with_service(service)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/middleware.py\", line 154, in _process_with_service
    response_message = service.process(request.headers, taxii_message)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/services/abstract.py\", line 89, in process
    in_response_to=message.message_id)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/exceptions.py\", line 48, in raise_failure
    tb=tb)
  File \"/usr/local/lib/python3.5/dist-packages/six.py\", line 692, in reraise
    raise value.with_traceback(tb)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/services/abstract.py\", line 83, in process
    response_message = handler.handle_message(self, message)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 126, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/taxii/services/handlers/inbox_message_handlers.py\", line 65, in handle_message
    inbox_message_id=inbox_message.id if inbox_message else None)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/persistence/manager.py\", line 160, in create_content
    content, collection_ids=collection_ids, service_id=service_id)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/persistence/sqldb/api.py\", line 249, in create_content_block
    self._attach_content_to_collections(content, collection_ids)
  File \"/usr/local/lib/python3.5/dist-packages/opentaxii/persistence/sqldb/api.py\", line 267, in _attach_content_to_collections
    collections=new_collections.count())
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 3089, in count
    return self.from_self(col).scalar()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2843, in scalar
    ret = self.one()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2814, in one
    ret = self.one_or_none()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2784, in one_or_none
    ret = list(self)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/query.py\", line 2854, in __iter__
    self.session._autoflush()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 1422, in _autoflush
    util.raise_from_cause(e)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 187, in reraise
    raise value
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 1412, in _autoflush
    self.flush()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 2192, in flush
    self._flush(objects)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 2312, in _flush
    transaction.rollback(_capture_exception=True)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/langhelpers.py\", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 187, in reraise
    raise value
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/session.py\", line 2276, in _flush
    flush_context.execute()
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py\", line 389, in execute
    rec.execute(self)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/unitofwork.py\", line 503, in execute
    self.dependency_processor.process_saves(uow, states)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/dependency.py\", line 1092, in process_saves
    secondary_update, secondary_delete)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/orm/dependency.py\", line 1136, in _run_crud
    connection.execute(statement, secondary_insert)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 945, in execute
    return meth(self, multiparams, params)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/sql/elements.py\", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1189, in _execute_context
    context)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1402, in _handle_dbapi_exception
    exc_info
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py\", line 186, in reraise
    raise value.with_traceback(tb)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py\", line 1182, in _execute_context
    context)
  File \"/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py\", line 470, in do_execute
    cursor.execute(statement, parameters)
opentaxii.taxii.exceptions.FailureStatus: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (sqlite3.IntegrityError) UNIQUE constraint failed: collection_to_content_block.collection_id, collection_to_content_block.content_block_id [SQL: 'INSERT INTO collection_to_content_block (collection_id, content_block_id) VALUES (?, ?)'] [parameters: (1, 1)]"
}
```

**Comment by arcsector** [comment] 2017-11-30 20:40
Could you please separate your error using line breaks? It makes it very hard to discern what's going on.

**Comment by arcsector** [comment] 2017-12-01 18:42
Thanks, much better. It sort of looks like it's a sqlite3 error (evidenced by the sqlite3.IntegrityError). Could you try doing this on a mysql backend or postgresql (whichever you're more comfortable with)? That may effect the behavior of the sql engine. If that doesn't work, in the meantime you could just use your own sqlalchemy or sqlsoup scrips to clear the database of all blocks.

**Comment by dhkron** [comment] 2017-12-06 13:59
I've tested it in PostgreSQL - the error occurs already in the deletion.

```
Traceback (most recent call last):
  File "/home/gil/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/home/gil/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: update or delete on table "content_blocks" violates foreign key constraint "collection_to_content_block_content_block_id_fkey" on table "collection_to_content_block"
DETAIL:  Key (id)=(1) is still referenced from table "collection_to_content_block".
```

**Comment by arcsector** [comment] 2017-12-06 15:44
This isn't an error with s
Opentaxii or sqlalchemy; it's a SQL error. If you go in and try to execute a DELETE statement on collection_to_content_block, you will get the same response.

I believe the way to correct this is to delete the content block first, then the collection, then the collection_to_content_block.

**Comment by traut** [comment] 2017-12-06 16:01
@dhkron by default sqllite3 [does not support foreign keys](https://stackoverflow.com/questions/5890250/on-delete-cascade-in-sqlite3#5901100). I suspect that's why `CASCADE`s do not work. Could you please verify?

**Comment by traut** [comment] 2017-12-06 16:03
regarding postgresql error -- it is strange, cascades are [in place](https://github.com/EclecticIQ/OpenTAXII/blob/master/opentaxii/persistence/sqldb/models.py#L21). Could you provide a description of that table in your DB?

**Comment by dhkron** [comment] 2017-12-07 09:13
This is the output of `\d+ collection_to_content_block` in psql.
```
                  Table "public.collection_to_content_block"
      Column      |  Type   | Modifiers | Storage | Stats target | Description 
------------------+---------+-----------+---------+--------------+-------------
 collection_id    | integer | not null  | plain   |              | 
 content_block_id | integer | not null  | plain   |              | 
Indexes:
    "collection_to_content_block_pkey" PRIMARY KEY, btree (collection_id, content_block_id)
    "ix_collection_to_content_block_content_block_id" btree (content_block_id)
Foreign-key constraints:
    "collection_to_content_block_collection_id_fkey" FOREIGN KEY (collection_id) REFERENCES data_collections(id)
    "collection_to_content_block_content_block_id_fkey" FOREIGN KEY (content_block_id) REFERENCES content_blocks(id)
```
Setup (all python is python3)
1) Start two PostgreSQL servers.
2) Start opentaxii machine
3) Add services, collections & a user (`opentaxii-create-services` etc)
4) Sanity test to services with `taxii-discovery`
5) Push data with a minimal `cabby` script & verify with `taxii-poll`
6) Then `opentaxii-delete-blocks` and boom!
```
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) update or delete on table "content_blocks" violates foreign key constraint "collection_to_content_block_content_block_id_fkey" on table "collection_to_content_block"
DETAIL:  Key (id)=(1) is still referenced from table "collection_to_content_block".
 [SQL: 'DELETE FROM content_blocks WHERE content_blocks.id IN (SELECT content_blocks.id \nFROM data_collections JOIN collection_to_content_block AS collection_to_content_block_1 ON data_collections.id = collection_to_content_block_1.collection_id JOIN content_blocks ON content_blocks.id = collection_to_content_block_1.content_block_id \nWHERE data_collections.id = %(id_1)s AND content_blocks.timestamp_label > %(timestamp_label_1)s AND content_blocks.timestamp_label <= %(timestamp_label_2)s)'] [parameters: {'id_1': 1, 'timestamp_label_1': '1970-01-01', 'timestamp_label_2': '2017-12-10'}]
```

**Comment by dhkron** [comment] 2017-12-12 13:35
I think the problems is related to the creation of the delete-cascade.
When I created the delete-cascade manually, it worked.
```
ALTER TABLE collection_to_content_block
DROP CONSTRAINT collection_to_content_block_content_block_id_fkey,
ADD CONSTRAINT collection_to_content_block_content_block_id_fkey
    FOREIGN KEY (content_block_id)
    REFERENCES content_blocks(id)
    ON DELETE CASCADE;
```

**Comment by traut** [comment] 2017-12-26 19:30
@dhkron thanks for extensive info on the issue. It seems cascades are not created automatically, which is strange, since sqlalchemy should take care of that. I'll look into it

**Comment by traut** [comment] 2018-06-03 21:43
closing this since I can not reproduce it. please comment if you can reproduce it in the latest [release 0.1.10](https://github.com/eclecticiq/OpenTAXII/releases/tag/0.1.10).

**Closed by traut** 2018-06-03 21:43 UTC
