### ISSUE TITLE
Postgre - Polling returns Binascii format

### ISSUE THREAD

**Issue by FloatingGhost** [EclecticIQ/OpenTAXII#79] opened 2017-07-27 11:00 UTC
Sorry, gotta bother you again.

I've run into a really weird issue - I switched to Postgres as the backend as
recommended, but it seems that everything is being sent around in what looks like
python's `binascii` format.

I've switched to sqlite and it works now, so no urgency, it's just a bit awkward >__<

```bash
# Create tables
$ opentaxii-create-services -c config/services.yaml
$ opentaxii-create-collections -c config/collections.yaml
# Account already created
$ opentaxii-run-dev # all runs fine

# Push a test file
$ taxii-push --username USER --password PASS --dest COLL --discovery
http://localhost/services/discovery -f test_files/campaign-v-actors.xml

2017-07-27 10:31:11,025 INFO: Sending Discovery_Request to
http://localhost/services/discovery
2017-07-27 10:31:11,027 INFO: Starting new HTTP connection (1): localhost
2017-07-27 10:31:11,208 INFO: 4 services discovered
2017-07-27 10:31:11,210 INFO: Sending Inbox_Message to http://localhost/services/inbox
2017-07-27 10:31:11,219 INFO: Starting new HTTP connection (1): localhost
2017-07-27 10:31:11,393 INFO: Content block successfully pushed

$ taxii-poll --username USER --password PASS -c COLL --discovery
http://localhost/services/discovery

2017-07-27 10:31:37,044 INFO: Polling using data binding: ALL
2017-07-27 10:31:37,048 INFO: Sending Discovery_Request to
http://localhost/services/discovery
2017-07-27 10:31:37,050 INFO: Starting new HTTP connection (1): localhost
2017-07-27 10:31:37,182 INFO: 4 services discovered
2017-07-27 10:31:37,183 INFO: Sending Poll_Request to http://localhost/services/poll
2017-07-27 10:31:37,185 INFO: Starting new HTTP connection (1): localhost

\x3c737469783a535449585f5 .. SNIP SNIP .. Basically a LOT of binascii
```

It's weird, I can poll taxiistand just fine, so it's not the client :<

Looks like it's stored in that format in the database - is that intended?

I've attached configuration files as well, I don't *think* there's anything wrong with
them though

Any idea what could cause this?

Versions:
sqlalchemy 1.2.0b2 (persists on 1.1.2)
cabby 0.1.18
OpenTaxii git HEAD

I think those are the only relevant ones

[services.txt](https://github.com/EclecticIQ/OpenTAXII/files/1179681/services.txt)
[config.txt](https://github.com/EclecticIQ/OpenTAXII/files/1179683/config.txt)
[collections.txt](https://github.com/EclecticIQ/OpenTAXII/files/1179682/collections.txt)

**Comment by FloatingGhost** [comment] 2017-07-27 11:09
Screenshot of the table content_blocks

Appears to binascii 

![2017-07-27-12-08-41](https://user-images.githubusercontent.com/4086403/28667658-652b1706-72c4-11e7-9d29-ae0794d12b59.png)

**Comment by traut** [comment] 2017-10-05 19:43
duplicate of to #80

**Closed by traut** 2017-10-05 19:43 UTC
