### ISSUE TITLE
Docker image install old version of opentaxiii resulting in silent fail of opentaxii-create-services

### ISSUE THREAD

**Issue by dbellavista** [eclecticiq/OpenTAXII#99] opened 2018-02-20 12:15 UTC
I tried to use the docker image as from the doc, but the configured services are not available: 

```
$ docker run -d -p 9000:9000 -v $(pwd):/input eclecticiq/opentaxii
$ taxii-discovery --host 127.0.0.1 --port 9000 --path /services/discovery-a
2018-02-20 12:55:01,320 INFO: Sending Discovery_Request to http://127.0.0.1:9000/services/discovery-a
2018-02-20 12:55:01,335 ERROR: HTTP Error: status code 404
```

So I tried to manually create the fixtures directly inside the docker:

```
$ docker exec -it 23d1dbe88c4b /bin/bash
root@23d1dbe88c4b:/# export OPENTAXII_CONFIG=/opentaxii.yml
root@23d1dbe88c4b:/# opentaxii-create-services -c /input/services.yml
bash: opentaxii-create-services: command not found
```

The installed version of opentaxii is `0.1.10a1`:

```
root@23d1dbe88c4b:/# pip search opentaxii
You are using pip version 6.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
opentaxii-server     - 
opentaxii            - TAXII server implementation in Python from EclecticIQ
  INSTALLED: 0.1.10a1
  LATEST:    0.1.9
opentaxii-client     - 
```
After installing the latest version:

```
root@23d1dbe88c4b:/# pip install opentaxii==0.1.9
root@23d1dbe88c4b:/# opentaxii-create-collections -c /input/collections.yml
2018-02-20T12:08:46.557427Z [opentaxii.utils] info: api.initialized {timestamp=2018-02-20T12:08:46.557427Z, logger=opentaxii.utils, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, event=api.initialized, level=info}
2018-02-20T12:08:46.564906Z [opentaxii.utils] info: api.initialized {timestamp=2018-02-20T12:08:46.564906Z, logger=opentaxii.utils, api=opentaxii.auth.sqldb.SQLDatabaseAPI, event=api.initialized, level=info}
2018-02-20T12:08:46.565190Z [opentaxii.server] info: opentaxii.server_configured {timestamp=2018-02-20T12:08:46.565190Z, logger=opentaxii.server, event=opentaxii.server_configured, level=info}
Loading: /input/collections.yml
2018-02-20T12:08:46.628099Z [opentaxii.persistence.manager] info: collection.created {timestamp=2018-02-20T12:08:46.628099Z, logger=opentaxii.persistence.manager, event=collection.created, collection=collection-A, level=info}
2018-02-20T12:08:46.653812Z [opentaxii.persistence.manager] info: collection.created {timestamp=2018-02-20T12:08:46.653812Z, logger=opentaxii.persistence.manager, event=collection.created, collection=collection-B, level=info}
2018-02-20T12:08:46.677267Z [opentaxii.persistence.manager] info: collection.created {timestamp=2018-02-20T12:08:46.677267Z, logger=opentaxii.persistence.manager, event=collection.created, collection=collection-C, level=info}
2018-02-20T12:08:46.696535Z [opentaxii.persistence.manager] info: collection.created {timestamp=2018-02-20T12:08:46.696535Z, logger=opentaxii.persistence.manager, event=collection.created, collection=collection-D, level=info}
root@23d1dbe88c4b:/# exit
```

The discovery works:

```
$ taxii-discovery --host 127.0.0.1 --port 9000 --path /services/discovery-a                                                                                          daniele@Danieles-MacBook-Pro
2018-02-20 13:05:29,766 INFO: Sending Discovery_Request to http://127.0.0.1:9000/services/discovery-a
2018-02-20 13:05:29,788 INFO: 7 services discovered
...
```
 

However by checking the installed version of `opentaxii` on the docker iamge

Using `services.yml` and `collections.yml` from the example in tag 0.1.9. However the command

**Comment by arcsector** [comment] 2018-02-20 15:11
Your comment ended quite abruptly there... Anything else you'd like to add?

To answer your question, this is because `opentaxii-create-services` is not used in the source version (latest release), but is used in the pip version (stable release). Sorry about the confusion.

**Comment by dbellavista** [comment] 2018-02-20 15:20
@arcsector sorry, I guess it's some kind of weird copy and paste. Actually the problem is that `entrypoint.sh` used by `docker` tries to execute `opentaxii-create-services` to populate services and such from `/inputs`. Since the command doesn't exists services and collections cannot be populated

**Comment by arcsector** [comment] 2018-02-27 01:41
Since this issue is just for the creation, updating, and deletion of db endpoints, a temporary solution would be to install create your services, accounts, and collections with `opentaxii-create-x` from outside of docker, and then (as long as you're not using sqlite, which you shouldn't be in production), you can just run the docker instance and it should work.

Did you also try my suggestion on using the latest release instead of stable, and trying `opentaxii-sync-data` instead?

**Comment by mwd102** [comment] 2018-05-22 22:37
This is also causing the official docker image to fail. The entrypoint is using the old commands but it is being built from the latest source.

**Comment by traut** [comment] 2018-06-04 13:32
docker script was updated and image re-created after 0.1.10 release, so I'm closing this. Please comment if this is still reproducible

**Closed by traut** 2018-06-04 13:32 UTC
